social_links:
  type: list
  list_type: simple
  default: "fab-github, Github, https://github.com/%s|fab-gitlab, Gitlab, https://gitlab.com/%s|fab-instagram, Instagram, https://instagram.com/%s|fab-twitter, Twitter, https://twitter.com/%s|fab-soundcloud, Soundcloud, http://soundcloud.com/%s|fab-spotify, Spotify, http://open.spotify.com/artist/%s|fab-bandcamp, Bandcamp, https://%s.bandcamp.com|envelope, Email Contact, mailto:%s|fab-linked-in, LinkedIn Profile, https://linkedin.com/in/%s|fab-youtube, Youtube, https://youtube.com/%s|fab-discord, Discord, https://discordapp.com/users/%s|fab-steam, Steam, https://steamcommunity.com/id/%s|fab-telegram, Telegram, https://t.me/%s|fab-tiktok, TikTok, https://tiktok.com/%s|fab-twitch, Twitch, https://twitch.tv/%s"
  description:
    en: "Comma delimited in this order: icon, user field name, URL<br><br>The URL must contain %s where it wants to substitute the value in 'user_field'."

# Defaults:
# fab-github, Github, https://github.com/%s
# fab-gitlab, Gitlab, https://gitlab.com/%s
# fab-instagram, Instagram, https://instagram.com/%s
# fab-twitter, Twitter, https://twitter.com/%s
# fab-soundcloud, Soundcloud, http://soundcloud.com/%s
# fab-spotify, Spotify, http://open.spotify.com/artist/%s
# fab-bandcamp, Bandcamp, https://%s.bandcamp.com
# envelope, Email Contact, mailto:%s
# fab-linked-in, LinkedIn Profile, https://linkedin.com/in/%s
# fab-youtube, Youtube, https://youtube.com/%s
# fab-discord, Discord, https://discordapp.com/users/%s
# fab-steam, Steam, https://steamcommunity.com/id/%s
# fab-telegram, Telegram, https://t.me/%s
# fab-tiktok, TikTok, https://tiktok.com/%s
# fab-twitch, Twitch, https://twitch.tv/%s

icon_color: 'var(--tertiary)'
